/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTaxCalendarRouteImport } from './routes/demo.tax-calendar'
import { Route as DemoSimulationsRouteImport } from './routes/demo.simulations'
import { Route as DemoSettingsRouteImport } from './routes/demo.settings'
import { Route as DemoOpportunitiesRouteImport } from './routes/demo.opportunities'
import { Route as DemoFinancingRouteImport } from './routes/demo.financing'
import { Route as DemoDashboardRouteImport } from './routes/demo.dashboard'
import { Route as DemoCostMonitorRouteImport } from './routes/demo.cost-monitor'
import { Route as DemoContractsRouteImport } from './routes/demo.contracts'
import { Route as DemoCashFlowRouteImport } from './routes/demo.cash-flow'
import { Route as DemoBusinessHealthRouteImport } from './routes/demo.business-health'
import { Route as DemoBalanceSheetsRouteImport } from './routes/demo.balance-sheets'
import { Route as DemoAiConsultantRouteImport } from './routes/demo.ai-consultant'
import { Route as DemoAccountingRouteImport } from './routes/demo.accounting'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/_app'
import { Route as AuthenticatedAppTaxCalendarRouteImport } from './routes/_authenticated/_app/tax-calendar'
import { Route as AuthenticatedAppSimulationsRouteImport } from './routes/_authenticated/_app/simulations'
import { Route as AuthenticatedAppSettingsRouteImport } from './routes/_authenticated/_app/settings'
import { Route as AuthenticatedAppOpportunitiesRouteImport } from './routes/_authenticated/_app/opportunities'
import { Route as AuthenticatedAppFinancingRouteImport } from './routes/_authenticated/_app/financing'
import { Route as AuthenticatedAppDashboardRouteImport } from './routes/_authenticated/_app/dashboard'
import { Route as AuthenticatedAppCostMonitorRouteImport } from './routes/_authenticated/_app/cost-monitor'
import { Route as AuthenticatedAppContractsRouteImport } from './routes/_authenticated/_app/contracts'
import { Route as AuthenticatedAppCashFlowRouteImport } from './routes/_authenticated/_app/cash-flow'
import { Route as AuthenticatedAppBusinessHealthRouteImport } from './routes/_authenticated/_app/business-health'
import { Route as AuthenticatedAppBalanceSheetsRouteImport } from './routes/_authenticated/_app/balance-sheets'
import { Route as AuthenticatedAppAiConsultantRouteImport } from './routes/_authenticated/_app/ai-consultant'
import { Route as AuthenticatedAppAccountingRouteImport } from './routes/_authenticated/_app/accounting'
import { Route as AuthenticatedAppDocumentsSalesRouteImport } from './routes/_authenticated/_app/documents.sales'
import { Route as AuthenticatedAppDocumentsPurchasesRouteImport } from './routes/_authenticated/_app/documents.purchases'
import { Route as AuthenticatedAppDocumentsOtherRouteImport } from './routes/_authenticated/_app/documents.other'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTaxCalendarRoute = DemoTaxCalendarRouteImport.update({
  id: '/tax-calendar',
  path: '/tax-calendar',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSimulationsRoute = DemoSimulationsRouteImport.update({
  id: '/simulations',
  path: '/simulations',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSettingsRoute = DemoSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DemoRoute,
} as any)
const DemoOpportunitiesRoute = DemoOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => DemoRoute,
} as any)
const DemoFinancingRoute = DemoFinancingRouteImport.update({
  id: '/financing',
  path: '/financing',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDashboardRoute = DemoDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCostMonitorRoute = DemoCostMonitorRouteImport.update({
  id: '/cost-monitor',
  path: '/cost-monitor',
  getParentRoute: () => DemoRoute,
} as any)
const DemoContractsRoute = DemoContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => DemoRoute,
} as any)
const DemoCashFlowRoute = DemoCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBusinessHealthRoute = DemoBusinessHealthRouteImport.update({
  id: '/business-health',
  path: '/business-health',
  getParentRoute: () => DemoRoute,
} as any)
const DemoBalanceSheetsRoute = DemoBalanceSheetsRouteImport.update({
  id: '/balance-sheets',
  path: '/balance-sheets',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAiConsultantRoute = DemoAiConsultantRouteImport.update({
  id: '/ai-consultant',
  path: '/ai-consultant',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAccountingRoute = DemoAccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => DemoRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppTaxCalendarRoute =
  AuthenticatedAppTaxCalendarRouteImport.update({
    id: '/tax-calendar',
    path: '/tax-calendar',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSimulationsRoute =
  AuthenticatedAppSimulationsRouteImport.update({
    id: '/simulations',
    path: '/simulations',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSettingsRoute =
  AuthenticatedAppSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOpportunitiesRoute =
  AuthenticatedAppOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppFinancingRoute =
  AuthenticatedAppFinancingRouteImport.update({
    id: '/financing',
    path: '/financing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDashboardRoute =
  AuthenticatedAppDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCostMonitorRoute =
  AuthenticatedAppCostMonitorRouteImport.update({
    id: '/cost-monitor',
    path: '/cost-monitor',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppContractsRoute =
  AuthenticatedAppContractsRouteImport.update({
    id: '/contracts',
    path: '/contracts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCashFlowRoute =
  AuthenticatedAppCashFlowRouteImport.update({
    id: '/cash-flow',
    path: '/cash-flow',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBusinessHealthRoute =
  AuthenticatedAppBusinessHealthRouteImport.update({
    id: '/business-health',
    path: '/business-health',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppBalanceSheetsRoute =
  AuthenticatedAppBalanceSheetsRouteImport.update({
    id: '/balance-sheets',
    path: '/balance-sheets',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiConsultantRoute =
  AuthenticatedAppAiConsultantRouteImport.update({
    id: '/ai-consultant',
    path: '/ai-consultant',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountingRoute =
  AuthenticatedAppAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsSalesRoute =
  AuthenticatedAppDocumentsSalesRouteImport.update({
    id: '/documents/sales',
    path: '/documents/sales',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsPurchasesRoute =
  AuthenticatedAppDocumentsPurchasesRouteImport.update({
    id: '/documents/purchases',
    path: '/documents/purchases',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppDocumentsOtherRoute =
  AuthenticatedAppDocumentsOtherRouteImport.update({
    id: '/documents/other',
    path: '/documents/other',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/demo/accounting': typeof DemoAccountingRoute
  '/demo/ai-consultant': typeof DemoAiConsultantRoute
  '/demo/balance-sheets': typeof DemoBalanceSheetsRoute
  '/demo/business-health': typeof DemoBusinessHealthRoute
  '/demo/cash-flow': typeof DemoCashFlowRoute
  '/demo/contracts': typeof DemoContractsRoute
  '/demo/cost-monitor': typeof DemoCostMonitorRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/financing': typeof DemoFinancingRoute
  '/demo/opportunities': typeof DemoOpportunitiesRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/simulations': typeof DemoSimulationsRoute
  '/demo/tax-calendar': typeof DemoTaxCalendarRoute
  '/accounting': typeof AuthenticatedAppAccountingRoute
  '/ai-consultant': typeof AuthenticatedAppAiConsultantRoute
  '/balance-sheets': typeof AuthenticatedAppBalanceSheetsRoute
  '/business-health': typeof AuthenticatedAppBusinessHealthRoute
  '/cash-flow': typeof AuthenticatedAppCashFlowRoute
  '/contracts': typeof AuthenticatedAppContractsRoute
  '/cost-monitor': typeof AuthenticatedAppCostMonitorRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/financing': typeof AuthenticatedAppFinancingRoute
  '/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/simulations': typeof AuthenticatedAppSimulationsRoute
  '/tax-calendar': typeof AuthenticatedAppTaxCalendarRoute
  '/documents/other': typeof AuthenticatedAppDocumentsOtherRoute
  '/documents/purchases': typeof AuthenticatedAppDocumentsPurchasesRoute
  '/documents/sales': typeof AuthenticatedAppDocumentsSalesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/demo/accounting': typeof DemoAccountingRoute
  '/demo/ai-consultant': typeof DemoAiConsultantRoute
  '/demo/balance-sheets': typeof DemoBalanceSheetsRoute
  '/demo/business-health': typeof DemoBusinessHealthRoute
  '/demo/cash-flow': typeof DemoCashFlowRoute
  '/demo/contracts': typeof DemoContractsRoute
  '/demo/cost-monitor': typeof DemoCostMonitorRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/financing': typeof DemoFinancingRoute
  '/demo/opportunities': typeof DemoOpportunitiesRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/simulations': typeof DemoSimulationsRoute
  '/demo/tax-calendar': typeof DemoTaxCalendarRoute
  '/accounting': typeof AuthenticatedAppAccountingRoute
  '/ai-consultant': typeof AuthenticatedAppAiConsultantRoute
  '/balance-sheets': typeof AuthenticatedAppBalanceSheetsRoute
  '/business-health': typeof AuthenticatedAppBusinessHealthRoute
  '/cash-flow': typeof AuthenticatedAppCashFlowRoute
  '/contracts': typeof AuthenticatedAppContractsRoute
  '/cost-monitor': typeof AuthenticatedAppCostMonitorRoute
  '/dashboard': typeof AuthenticatedAppDashboardRoute
  '/financing': typeof AuthenticatedAppFinancingRoute
  '/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/settings': typeof AuthenticatedAppSettingsRoute
  '/simulations': typeof AuthenticatedAppSimulationsRoute
  '/tax-calendar': typeof AuthenticatedAppTaxCalendarRoute
  '/documents/other': typeof AuthenticatedAppDocumentsOtherRoute
  '/documents/purchases': typeof AuthenticatedAppDocumentsPurchasesRoute
  '/documents/sales': typeof AuthenticatedAppDocumentsSalesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/demo': typeof DemoRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/_app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/demo/accounting': typeof DemoAccountingRoute
  '/demo/ai-consultant': typeof DemoAiConsultantRoute
  '/demo/balance-sheets': typeof DemoBalanceSheetsRoute
  '/demo/business-health': typeof DemoBusinessHealthRoute
  '/demo/cash-flow': typeof DemoCashFlowRoute
  '/demo/contracts': typeof DemoContractsRoute
  '/demo/cost-monitor': typeof DemoCostMonitorRoute
  '/demo/dashboard': typeof DemoDashboardRoute
  '/demo/financing': typeof DemoFinancingRoute
  '/demo/opportunities': typeof DemoOpportunitiesRoute
  '/demo/settings': typeof DemoSettingsRoute
  '/demo/simulations': typeof DemoSimulationsRoute
  '/demo/tax-calendar': typeof DemoTaxCalendarRoute
  '/_authenticated/_app/accounting': typeof AuthenticatedAppAccountingRoute
  '/_authenticated/_app/ai-consultant': typeof AuthenticatedAppAiConsultantRoute
  '/_authenticated/_app/balance-sheets': typeof AuthenticatedAppBalanceSheetsRoute
  '/_authenticated/_app/business-health': typeof AuthenticatedAppBusinessHealthRoute
  '/_authenticated/_app/cash-flow': typeof AuthenticatedAppCashFlowRoute
  '/_authenticated/_app/contracts': typeof AuthenticatedAppContractsRoute
  '/_authenticated/_app/cost-monitor': typeof AuthenticatedAppCostMonitorRoute
  '/_authenticated/_app/dashboard': typeof AuthenticatedAppDashboardRoute
  '/_authenticated/_app/financing': typeof AuthenticatedAppFinancingRoute
  '/_authenticated/_app/opportunities': typeof AuthenticatedAppOpportunitiesRoute
  '/_authenticated/_app/settings': typeof AuthenticatedAppSettingsRoute
  '/_authenticated/_app/simulations': typeof AuthenticatedAppSimulationsRoute
  '/_authenticated/_app/tax-calendar': typeof AuthenticatedAppTaxCalendarRoute
  '/_authenticated/_app/documents/other': typeof AuthenticatedAppDocumentsOtherRoute
  '/_authenticated/_app/documents/purchases': typeof AuthenticatedAppDocumentsPurchasesRoute
  '/_authenticated/_app/documents/sales': typeof AuthenticatedAppDocumentsSalesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/onboarding'
    | '/demo/accounting'
    | '/demo/ai-consultant'
    | '/demo/balance-sheets'
    | '/demo/business-health'
    | '/demo/cash-flow'
    | '/demo/contracts'
    | '/demo/cost-monitor'
    | '/demo/dashboard'
    | '/demo/financing'
    | '/demo/opportunities'
    | '/demo/settings'
    | '/demo/simulations'
    | '/demo/tax-calendar'
    | '/accounting'
    | '/ai-consultant'
    | '/balance-sheets'
    | '/business-health'
    | '/cash-flow'
    | '/contracts'
    | '/cost-monitor'
    | '/dashboard'
    | '/financing'
    | '/opportunities'
    | '/settings'
    | '/simulations'
    | '/tax-calendar'
    | '/documents/other'
    | '/documents/purchases'
    | '/documents/sales'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/onboarding'
    | '/demo/accounting'
    | '/demo/ai-consultant'
    | '/demo/balance-sheets'
    | '/demo/business-health'
    | '/demo/cash-flow'
    | '/demo/contracts'
    | '/demo/cost-monitor'
    | '/demo/dashboard'
    | '/demo/financing'
    | '/demo/opportunities'
    | '/demo/settings'
    | '/demo/simulations'
    | '/demo/tax-calendar'
    | '/accounting'
    | '/ai-consultant'
    | '/balance-sheets'
    | '/business-health'
    | '/cash-flow'
    | '/contracts'
    | '/cost-monitor'
    | '/dashboard'
    | '/financing'
    | '/opportunities'
    | '/settings'
    | '/simulations'
    | '/tax-calendar'
    | '/documents/other'
    | '/documents/purchases'
    | '/documents/sales'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/demo'
    | '/sitemap.xml'
    | '/_authenticated/_app'
    | '/_authenticated/onboarding'
    | '/demo/accounting'
    | '/demo/ai-consultant'
    | '/demo/balance-sheets'
    | '/demo/business-health'
    | '/demo/cash-flow'
    | '/demo/contracts'
    | '/demo/cost-monitor'
    | '/demo/dashboard'
    | '/demo/financing'
    | '/demo/opportunities'
    | '/demo/settings'
    | '/demo/simulations'
    | '/demo/tax-calendar'
    | '/_authenticated/_app/accounting'
    | '/_authenticated/_app/ai-consultant'
    | '/_authenticated/_app/balance-sheets'
    | '/_authenticated/_app/business-health'
    | '/_authenticated/_app/cash-flow'
    | '/_authenticated/_app/contracts'
    | '/_authenticated/_app/cost-monitor'
    | '/_authenticated/_app/dashboard'
    | '/_authenticated/_app/financing'
    | '/_authenticated/_app/opportunities'
    | '/_authenticated/_app/settings'
    | '/_authenticated/_app/simulations'
    | '/_authenticated/_app/tax-calendar'
    | '/_authenticated/_app/documents/other'
    | '/_authenticated/_app/documents/purchases'
    | '/_authenticated/_app/documents/sales'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  DemoRoute: typeof DemoRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tax-calendar': {
      id: '/demo/tax-calendar'
      path: '/tax-calendar'
      fullPath: '/demo/tax-calendar'
      preLoaderRoute: typeof DemoTaxCalendarRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/simulations': {
      id: '/demo/simulations'
      path: '/simulations'
      fullPath: '/demo/simulations'
      preLoaderRoute: typeof DemoSimulationsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/settings': {
      id: '/demo/settings'
      path: '/settings'
      fullPath: '/demo/settings'
      preLoaderRoute: typeof DemoSettingsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/opportunities': {
      id: '/demo/opportunities'
      path: '/opportunities'
      fullPath: '/demo/opportunities'
      preLoaderRoute: typeof DemoOpportunitiesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/financing': {
      id: '/demo/financing'
      path: '/financing'
      fullPath: '/demo/financing'
      preLoaderRoute: typeof DemoFinancingRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/dashboard': {
      id: '/demo/dashboard'
      path: '/dashboard'
      fullPath: '/demo/dashboard'
      preLoaderRoute: typeof DemoDashboardRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/cost-monitor': {
      id: '/demo/cost-monitor'
      path: '/cost-monitor'
      fullPath: '/demo/cost-monitor'
      preLoaderRoute: typeof DemoCostMonitorRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/contracts': {
      id: '/demo/contracts'
      path: '/contracts'
      fullPath: '/demo/contracts'
      preLoaderRoute: typeof DemoContractsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/cash-flow': {
      id: '/demo/cash-flow'
      path: '/cash-flow'
      fullPath: '/demo/cash-flow'
      preLoaderRoute: typeof DemoCashFlowRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/business-health': {
      id: '/demo/business-health'
      path: '/business-health'
      fullPath: '/demo/business-health'
      preLoaderRoute: typeof DemoBusinessHealthRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/balance-sheets': {
      id: '/demo/balance-sheets'
      path: '/balance-sheets'
      fullPath: '/demo/balance-sheets'
      preLoaderRoute: typeof DemoBalanceSheetsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/ai-consultant': {
      id: '/demo/ai-consultant'
      path: '/ai-consultant'
      fullPath: '/demo/ai-consultant'
      preLoaderRoute: typeof DemoAiConsultantRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/accounting': {
      id: '/demo/accounting'
      path: '/accounting'
      fullPath: '/demo/accounting'
      preLoaderRoute: typeof DemoAccountingRouteImport
      parentRoute: typeof DemoRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app': {
      id: '/_authenticated/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_app/tax-calendar': {
      id: '/_authenticated/_app/tax-calendar'
      path: '/tax-calendar'
      fullPath: '/tax-calendar'
      preLoaderRoute: typeof AuthenticatedAppTaxCalendarRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/simulations': {
      id: '/_authenticated/_app/simulations'
      path: '/simulations'
      fullPath: '/simulations'
      preLoaderRoute: typeof AuthenticatedAppSimulationsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/settings': {
      id: '/_authenticated/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedAppSettingsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/opportunities': {
      id: '/_authenticated/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedAppOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/financing': {
      id: '/_authenticated/_app/financing'
      path: '/financing'
      fullPath: '/financing'
      preLoaderRoute: typeof AuthenticatedAppFinancingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/dashboard': {
      id: '/_authenticated/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedAppDashboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cost-monitor': {
      id: '/_authenticated/_app/cost-monitor'
      path: '/cost-monitor'
      fullPath: '/cost-monitor'
      preLoaderRoute: typeof AuthenticatedAppCostMonitorRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/contracts': {
      id: '/_authenticated/_app/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedAppContractsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/cash-flow': {
      id: '/_authenticated/_app/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof AuthenticatedAppCashFlowRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/business-health': {
      id: '/_authenticated/_app/business-health'
      path: '/business-health'
      fullPath: '/business-health'
      preLoaderRoute: typeof AuthenticatedAppBusinessHealthRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/balance-sheets': {
      id: '/_authenticated/_app/balance-sheets'
      path: '/balance-sheets'
      fullPath: '/balance-sheets'
      preLoaderRoute: typeof AuthenticatedAppBalanceSheetsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/ai-consultant': {
      id: '/_authenticated/_app/ai-consultant'
      path: '/ai-consultant'
      fullPath: '/ai-consultant'
      preLoaderRoute: typeof AuthenticatedAppAiConsultantRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/accounting': {
      id: '/_authenticated/_app/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AuthenticatedAppAccountingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/documents/sales': {
      id: '/_authenticated/_app/documents/sales'
      path: '/documents/sales'
      fullPath: '/documents/sales'
      preLoaderRoute: typeof AuthenticatedAppDocumentsSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/documents/purchases': {
      id: '/_authenticated/_app/documents/purchases'
      path: '/documents/purchases'
      fullPath: '/documents/purchases'
      preLoaderRoute: typeof AuthenticatedAppDocumentsPurchasesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/_app/documents/other': {
      id: '/_authenticated/_app/documents/other'
      path: '/documents/other'
      fullPath: '/documents/other'
      preLoaderRoute: typeof AuthenticatedAppDocumentsOtherRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountingRoute: typeof AuthenticatedAppAccountingRoute
  AuthenticatedAppAiConsultantRoute: typeof AuthenticatedAppAiConsultantRoute
  AuthenticatedAppBalanceSheetsRoute: typeof AuthenticatedAppBalanceSheetsRoute
  AuthenticatedAppBusinessHealthRoute: typeof AuthenticatedAppBusinessHealthRoute
  AuthenticatedAppCashFlowRoute: typeof AuthenticatedAppCashFlowRoute
  AuthenticatedAppContractsRoute: typeof AuthenticatedAppContractsRoute
  AuthenticatedAppCostMonitorRoute: typeof AuthenticatedAppCostMonitorRoute
  AuthenticatedAppDashboardRoute: typeof AuthenticatedAppDashboardRoute
  AuthenticatedAppFinancingRoute: typeof AuthenticatedAppFinancingRoute
  AuthenticatedAppOpportunitiesRoute: typeof AuthenticatedAppOpportunitiesRoute
  AuthenticatedAppSettingsRoute: typeof AuthenticatedAppSettingsRoute
  AuthenticatedAppSimulationsRoute: typeof AuthenticatedAppSimulationsRoute
  AuthenticatedAppTaxCalendarRoute: typeof AuthenticatedAppTaxCalendarRoute
  AuthenticatedAppDocumentsOtherRoute: typeof AuthenticatedAppDocumentsOtherRoute
  AuthenticatedAppDocumentsPurchasesRoute: typeof AuthenticatedAppDocumentsPurchasesRoute
  AuthenticatedAppDocumentsSalesRoute: typeof AuthenticatedAppDocumentsSalesRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountingRoute: AuthenticatedAppAccountingRoute,
  AuthenticatedAppAiConsultantRoute: AuthenticatedAppAiConsultantRoute,
  AuthenticatedAppBalanceSheetsRoute: AuthenticatedAppBalanceSheetsRoute,
  AuthenticatedAppBusinessHealthRoute: AuthenticatedAppBusinessHealthRoute,
  AuthenticatedAppCashFlowRoute: AuthenticatedAppCashFlowRoute,
  AuthenticatedAppContractsRoute: AuthenticatedAppContractsRoute,
  AuthenticatedAppCostMonitorRoute: AuthenticatedAppCostMonitorRoute,
  AuthenticatedAppDashboardRoute: AuthenticatedAppDashboardRoute,
  AuthenticatedAppFinancingRoute: AuthenticatedAppFinancingRoute,
  AuthenticatedAppOpportunitiesRoute: AuthenticatedAppOpportunitiesRoute,
  AuthenticatedAppSettingsRoute: AuthenticatedAppSettingsRoute,
  AuthenticatedAppSimulationsRoute: AuthenticatedAppSimulationsRoute,
  AuthenticatedAppTaxCalendarRoute: AuthenticatedAppTaxCalendarRoute,
  AuthenticatedAppDocumentsOtherRoute: AuthenticatedAppDocumentsOtherRoute,
  AuthenticatedAppDocumentsPurchasesRoute:
    AuthenticatedAppDocumentsPurchasesRoute,
  AuthenticatedAppDocumentsSalesRoute: AuthenticatedAppDocumentsSalesRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DemoRouteChildren {
  DemoAccountingRoute: typeof DemoAccountingRoute
  DemoAiConsultantRoute: typeof DemoAiConsultantRoute
  DemoBalanceSheetsRoute: typeof DemoBalanceSheetsRoute
  DemoBusinessHealthRoute: typeof DemoBusinessHealthRoute
  DemoCashFlowRoute: typeof DemoCashFlowRoute
  DemoContractsRoute: typeof DemoContractsRoute
  DemoCostMonitorRoute: typeof DemoCostMonitorRoute
  DemoDashboardRoute: typeof DemoDashboardRoute
  DemoFinancingRoute: typeof DemoFinancingRoute
  DemoOpportunitiesRoute: typeof DemoOpportunitiesRoute
  DemoSettingsRoute: typeof DemoSettingsRoute
  DemoSimulationsRoute: typeof DemoSimulationsRoute
  DemoTaxCalendarRoute: typeof DemoTaxCalendarRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoAccountingRoute: DemoAccountingRoute,
  DemoAiConsultantRoute: DemoAiConsultantRoute,
  DemoBalanceSheetsRoute: DemoBalanceSheetsRoute,
  DemoBusinessHealthRoute: DemoBusinessHealthRoute,
  DemoCashFlowRoute: DemoCashFlowRoute,
  DemoContractsRoute: DemoContractsRoute,
  DemoCostMonitorRoute: DemoCostMonitorRoute,
  DemoDashboardRoute: DemoDashboardRoute,
  DemoFinancingRoute: DemoFinancingRoute,
  DemoOpportunitiesRoute: DemoOpportunitiesRoute,
  DemoSettingsRoute: DemoSettingsRoute,
  DemoSimulationsRoute: DemoSimulationsRoute,
  DemoTaxCalendarRoute: DemoTaxCalendarRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  DemoRoute: DemoRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
